### ISSUE TITLE
Feature: Possibility to skip the dialog box and use the mouse to move animated parts directly

### ISSUE THREAD

**Issue by luzpaz** [unrealmatthews/fcmc-adapter#1]
That would be a pretty sweet feature

**Comment by heissgetraenk** [comment]
The purpose of the adapter is to provide an external application with access to a FreeCad model. The long-term goal is a digital twin/virtual commissioning sort of affair, for testing machine software on a CAD model. So unfortunately your feature is not in the scope of what I am trying to achieve.
